### ISSUE TITLE
Can not use .env.local in a setup without --mode argument

### ISSUE THREAD

**Issue by olederle** [ponjs/craco-plugin-env#1]
If the `--mode` argument is not used, index is '-1' and in that case the first entry of the `argv` is used (-1 + 1 = 0), which might be something like `/path/to/node/node`.

https://github.com/ponjs/craco-plugin-env/blob/13a5284467ffdce269a9403abc8ca36e5c6c686c/index.js#L8

The resolved **localPath** is then something like: `/path/to/project.env./path/to/node/node.local`

Maybe it's better to use something like `return index !== -1 ? process.argv[index + 1] : ''`

**Comment by ponjs** [comment]
Thank you for finding the issues, it has now been revised and the concurrent version 1.0.4.
