### ISSUE TITLE
Modify default path for .env files when using react-scripts (CRA)?

### ISSUE THREAD

**Issue by nirpeled** [ponjs/craco-plugin-env#2]
Seems like react-scripts (CRA) is using an hard-coded path for reading the .env files (reading from project's folder).

How can I use craco or this craco plugin to override it?

Thanks :)

**Comment by ponjs** [comment]
Yes, react-scripts (CRA) reads the .env file in the application root directory, as does craco-plugin-env. This is because we generally put .env files here.

**Comment by nirpeled** [comment]
@ponjs My problem with that is that I have a monorepo with multiple apps (using yarn workspaces) and CRA looks for the .env within the app's folder and not the global root folder, that's why I'm looking for a way to modify it, any ideas?

**Comment by ponjs** [comment]
If you are using `Yarn Workspaces`, you will read the `.env` file under the workspace, but will not read it to the project root path.
But if you want to do it, you can do this:

```js
// packages/your-package/craco.config.js

const CracoEnvPlugin = require('craco-plugin-env')
const dotenv = require('dotenv')
const path = require('path')
const fs = require('fs')

const loadRootEnv = () => {
  try {
    const envPath = path.resolve(__dirname, '../../.env')
    const env = fs.readFileSync(envPath)
    return dotenv.parse(env)
  } catch (error) {
    return {}
  }
}

module.exports = {
  plugins: [
    {
      plugin: CracoEnvPlugin,
      options: {
        variables: {
          ...loadRootEnv()
        }
      }
    }
  ]
}
```

**Comment by smac89** [comment]
The above solution is not very robust.

I also use a monorepo, and would have preferred an option that allowed me atleast specify the location of the root folder where the `.env*` files are stored, aka the [`path`](https://github.com/motdotla/dotenv#path) option from `dotenv`. This way I could use something like [`find-yarn-workspace-root`](https://github.com/square/find-yarn-workspace-root) and pass the result to the config.

IMO, the best way is to allow users to configure the [options](https://github.com/motdotla/dotenv#options) passed to `dotenv.config({...})`, and one of these options is the `path` option I mentioned.
